#!/bin/bash

BRIGHTNESS=`xrandr --verbose | grep -i brightness | cut -f2 -d ' ' | head -n1`

BRIGHTNESS=$(echo "$BRIGHTNESS 100" | awk '{printf "%f", $1 * $2}')

BRIGHTNESS=${BRIGHTNESS%.*}

echo $BRIGHTNESS%

